language: go
dist: bionic

go: 1.18.x

notifications:
  slack:
    rooms:
      - secure: "sQvFIw66iHRO0opnKa6IuSQVPPBbzzgcTZBIZCUWVCR9r1/LSNEX27iVipOqqQmp4kvzj4aehYIGbb9LGGi6UsykQjfaKDjLzQXXs55XNWpx/dYzlgMXK9cq8jufc47XE58z3dBhO6d9KtHtgon5G1gFGGHh3U1K6EwQDcBGi8ymH+RF40sN8JRE46CQZVDYdfJP4pVg/KPCkwi+QNIU06qPPrt7vuyV3tvEBt6CQttugpP6t/OOC3viGKmmCOgTjCqlc28i9JmvZX07T27y6uMbmqpBcq4OJfaTMl4GtHsiG6+bvGb4pkd51TS2ujQ7tpjhxtTss6S1IGSi2t+bEuWzSVpTx8H6NsAq+u+d2iZ6Fc78uAVKnHA3FBdmgWT4MsL7n2B2Ppv66374mCv+QF5y+R2WkBvSSKSXeWaOonyXG1/Wtvp+eJQ0Tt/UCKxi1bIX1ugNnb9u/dTgqME+Cq4cevgYErEXeOwNthTgbf2DaUo65RTAxTdNCZgISguHoZXBpre93tjR0RAkaY73lwpbrXHHC65VwrhYRtdCJ6bH0vmUsfht+lRnqzIdklFvUMOeF2fqOBwk0v3PQSYaXSqdFbuvsXH3P92c5gfSiySnrDWFEONTxInBWytiLrL7uGIedWbS+mbiBBXR77SwoHc+7Qm+ynj+cxZK/GlXE90="
    on_success: change
    on_failure: change

branches:
  only:
    - master

jobs:
  include:
  - stage: lint
    script: helm lint yilu-common --set image.tag="test"
    install: ./scripts/install_toolchain.sh

  - stage: package and publish
    script: ./scripts/publish_chart.sh
    ##TODO later use gh-pages branch
    if: type != pull_request AND branch = master
    install: ./scripts/install_toolchain.sh
    env:
    # TRAVIS_GITHUB_TOKEN
    - secure: "FB9gv06DVMzy4074a3jZIkrGRQpsCYUb20JW126mSuzsSgHdBRtEO+qIdLqgFBQ8zp/L8Q1U8dG+XmcX8euDe3FVAuENWMSbd/uEeteP621Gj6lkkzGhqbBzFAXLWpoLXO1a3OpZoKbdCVmXdem+FTgFJReNiD5MJg1tRKkT8+qs5WjRxLxo3ot+4lnf6vpiijF8UBnFOwG9v8XpQFEG0S1+66mjAEcVqaeX1RPlYZ6otJSvMmbGTIde5YymKYfOED2VY5YQ1CA6KtM4ZdrgQ61BTbddTXdFxWm7Z2RJeVj3O7u6VrGuOvbGnfgzQc75LM8jzYRRoyHbA/1scniHap2M/30riSfyG1F5h7J7bweZ1/h2SJhAS7/dRLFcAg5GfhS2wEQeKoLObT8AEmW1Q29kpN2PEuBWhECWVlsoyH/RwLnyGZPbNqManiSbC3Brzno2ghO3LFmNuDt62slFZIN4NPjvx5BQasUUVgD8oQzmdW4D8QdtULa0Vt1JOBgp72ADpmAw8X6HajMeC8VgDEc9Qj5vjYXygrx7kVJaBPqwIFQ9aIBoUpNwbDGn1woSQx8K6V0HA8r97xFW39wnlo2eGGsOBiQsa7xoz1VNroQ19zPoUZsMUm+GclTHsrZFV7UYkFFD7jABLhiK6tLFXKAzaFI0MRp5YxLd2nKsQKM="
