language: go
dist: bionic
os: linux
go: 1.18.x

notifications:
  slack:
    rooms:
      - secure: "lJHDtsla4rDNbmsxxDjCaHPhrqNcSIFrzPNnK7sPucf+NG0Okfeqzeh/qy0AjnVUBusnnqlXdzpvPLyZF5KcTSLpfgFWINXqKvOy8cBbLSXKPwSOnB7btbv4Cx36YnJTBzdVjSzuM7biypCtSv2kI10rHwLeaA6r4ZMEog83CWbLKmxq6+sDQGALPrfy5uz29BIJxYTIcG2gLzmof5Fe9oIZCTg+RO363h9+OY+NeHmfrN3jtBUXT9K3QYIsmPDazjKSQhQ1yAo1+2MM1ajpM88Up5VXJkOc+KUnunqdRjhrVzcvVDwZW9ZtIzNkddWUou5GzusMpZ0xXfBUqRbRYdmHMwV4s6oLdW3ysioWj4HJXGY5zoQoSifH9RR5YqIBNYk4JOy5eeRRSZr84UU5iHsKnrQHYzGYl12e3zu5JzYTdMS7NICk/AHREMs1YLyV96IYhzZyNLfWA6U/k/r33kd73r351w5i9wVZzgl1v4Jkh2glT7DspBN05GwoqF8UhfV95YpyPgF40Ihvxe7MPwjv6rk10Tki7uECoZyzcpeZlcPYS9Nrsocg4RPNt/IEokUG3jrC0V7A4acVIdjPWw5Yvpeek+fC1qnABKt0c9NzaPtWTXEPaHBzIdGKQGVeno5x2XrGeonu0O8mSfnbuqmVb6nIa+0wrM7OKWUlHFM="
    on_success: change
    on_failure: change

branches:
  only:
    - master

jobs:
  include:
  - stage: lint
    script: helm lint yilu-common --set image.tag="test" --set serviceName="ci-test"
    install: ./scripts/install_toolchain.sh

  - stage: package and publish
    script: ./scripts/publish_chart.sh
#   TODO later consider using gh-pages branch
    if: type != pull_request AND ( branch = master )
    install: ./scripts/install_toolchain.sh
    env:
      # TRAVIS_GITHUB_TOKEN
      - secure: "Graa+EAfqre5voXHbfE6RPgeYDTCXqz5STZCvY10X48jY4So8ZYWxELfLxSXkzMhQ0A4QXp4jXnbASNnYRUJ5SPtx8FmagtBAZIk2ZODRs9dSra36WVjYzNaWHyUZpZEcrHERxhUnhllFr+OVamGOhdJFuZoAquUjLGzdiwA1V+smbi0KiEEDaQipqgQm7FJO7zV+56+HMLHuAYe0UvGwdCEt6y/K+l5Ooz2/HRHeeh3+pbI3KgSRQyQnXlogfPEjLKQ17PrtYxGLjptv6dEjC2OafE6ooci0h4H3chG3p7WzSM2Cc2HntA97JyEsf1g1LX/TmMAdB2Skg/HqrTREScagmAJzHFvswyZmSkZHSCsA7fzuG8dmEI1mrTt5HdJGKJDiaNt6HElmo0eOf5S02aoluK69+FltYZrvXgEqx74p5SEkhbNgsHoF+WoixJYuSrvhf7c34fvmechcXpmFI0QpEN2/9HaKYk82IbzXLOt2xiidMpug0CpcrStVnAOjHkq/eGgHOqkoOvSQ7c0v95lhLIemfHdoH746ivZkvBvl4n6nTwJHjU1oaBrnnUT0IQqI1HzLNZm7GG/5zN8ybQF5QzRs+GDSC5xdgAdeyRxQQSDqeeL3eMNnY/WwJYyu4qNyS3r5hhtOOs3F8oU3sX9OY+6i7PwnZbLw7YUDE8="
