{{- define "common.cronjob" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
{{- if .Values.job }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "common.name" . }}
spec:
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy }}
  schedule: {{ .Values.job.schedule }}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            simpletrip: {{ include "common.name" . }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ include "common.containerName" . }}
              image: {{- if .Values.job.overrideImageUrl }} {{ .Values.job.overrideImageUrl }} {{ else }} {{ .Values.imageRepository }}/{{ template "common.name" . }}:{{ .Values.imageTag }} {{- end }}
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              {{- if .Values.job.command }}
              command: {{ .Values.job.command }}
              {{- end }}
              {{- with .Values.job.args }}
              args:
{{ toYaml . | indent 16 }}
              {{- end }}
              {{- if .Values.job.extraEnvConfigMapRef }}
              envFrom:
                - configMapRef:
                    name: {{ .Values.job.extraEnvConfigMapRef }}
              {{- end }}
              env:
              - name: DD_AGENT_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: {{ .Values.datadogServiceNameEnv}}
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['simpletrip']
                {{- if .Values.autoTraceIdInjection }}
              - name: DD_LOGS_INJECTION
                value: 'true'
                {{- end }}
                {{- if .Values.traceAnalyticsEnabled }}
              - name: DD_TRACE_ANALYTICS_ENABLED
                value: 'true'
                {{- end }}
                {{- if .Values.analyzedSpansEnabled }}
              - name: DD_APM_ANALYZED_SPANS
                value: 'true'
                {{- end }}
{{- end }}
{{- end }}
{{- end }}
