{{- if .Values.job.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "common.name" . }}
spec:
  concurrencyPolicy: {{ .Values.job.concurrencyPolicy }}
  schedule: {{ .Values.job.schedule }}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            simpletrip: {{ include "common.name" . }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ include "common.containerName" . }}
              image: {{- if .Values.job.overrideImageUrl }} {{ .Values.job.overrideImageUrl }} {{ else }} {{ .Values.image.repository }}/{{ template "common.name" . }}:{{ .Values.image.tag }} {{- end }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              {{- if .Values.job.command }}
              command: {{ .Values.job.command }}
              {{- end }}
              {{- if .Values.job.args }}
              args: {{- include "common.tplvalues.render" (dict "value" .Values.job.args "context" $) | nindent 16 }}
              {{- end }}
              {{- if .Values.job.extraEnvConfigMapRef }}
              envFrom:
                - configMapRef:
                    name: {{ .Values.job.c }}
              {{- end }}
              env:
              - name: DD_AGENT_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: {{ .Values.datadog.serviceNameEnv}}
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['simpletrip']
                {{- if .Values.datadog.autoTraceIdInjection }}
              - name: DD_LOGS_INJECTION
                value: 'true'
                {{- end }}
                {{- if .Values.datadog.traceAnalyticsEnabled }}
              - name: DD_TRACE_ANALYTICS_ENABLED
                value: 'true'
                {{- end }}
                {{- if .Values.datadog.analyzedSpansEnabled }}
              - name: DD_APM_ANALYZED_SPANS
                value: 'true'
                {{- end }}
{{- end }}
