{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "24h"
  target:
    name: {{ .Values.secrets.name }}
  data:
    - secretKey: application.yaml
      remoteRef:
        key: kv/services/secrets/data/{{ .Values.secrets.name }}
        property: application.yaml
        decodingStrategy: Base64
{{- end }}
