{{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "{{ .Values.secrets.refreshInterval }}"
  target:
    name: {{ .Values.secrets.name }}
  data:
    - secretKey: {{ .Values.secrets.data.secretKey }}
      remoteRef:
        key: {{ .Values.secrets.data.remoteRef.parentKey }}/{{ .Values.secrets.name }}
        property: {{ .Values.secrets.data.remoteRef.property }}
        decodingStrategy: {{ .Values.secrets.data.remoteRef.decodingStrategy }}
{{- end }}
