apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}
  labels:
    simpletrip: {{ include "common.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: http
{{- if .Values.service.https.enabled }}
  - port: {{ .Values.service.https.port }}
    name: https
{{- end }}
  selector:
    simpletrip: {{ include "common.name" . }}
