{{- if .Values.secrets.enabled }}
{{- $VaultDynamicSecret := lookup "secrets.hashicorp.com/v1beta1" "VaultDynamicSecret" .Release.Namespace .Values.secrets.name -}}
{{- $ServiceAccount := lookup "v1" "ServiceAccount" .Release.Namespace "vault-secrets-operator-sa" -}}
{{- $Secret := lookup "v1" "Secret" .Release.Namespace "vault-secrets-operator-sa-secret" -}}
{{- $ClusterRoleBinding := lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "{{ .Release.Name }}-role-tokenreview-binding" -}}

{{- if not $VaultDynamicSecret -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    simpletrip: {{ include "common.name" . }}
    imageTag: {{ quote .Values.image.tag }}
spec:
  namespace: {{ .Values.secrets.vault.namespace }}
  vaultAuthRef: {{ .Values.secrets.vault.authRef }}
  mount: {{ .Values.secrets.vault.secretsEngineMount }}
  path: {{ .Values.secrets.vault.awsPermissionsRole }}
  destination:
    name: {{ .Values.secrets.name }}
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "common.name" . }}
{{- end }}

---
{{- if not $ServiceAccount -}}
# The name of this service account must match that defined in the vault secrets operator namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secrets.vault.vaultSecretsOperatorName }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}

---
{{- if not $Secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.vault.vaultSecretsOperatorName }}-sa-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.secrets.vault.vaultSecretsOperatorName }}-sa
type: kubernetes.io/service-account-token
{{- end }}

---
{{- if not $ClusterRoleBinding -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.secrets.vault.vaultSecretsOperatorName }}-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
