{{- $serviceName := (include "common.name" .) -}}
{{- $namespace := .Values.secrets.vault.namespace -}}
{{- $vaultAuthRef := .Values.secrets.vault.authRef -}}


{{- if .Values.secrets.staticSecrets.enabled }}
{{- range .Values.secrets.staticSecrets.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .secretName }}
  labels:
    simpletrip: {{ $serviceName }}
spec:
  namespace: {{ $namespace }}
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ .mountPath }}
  type: {{ .type }}
  path: {{  .secretPath }}
  {{- if .version -}}
  version: {{ .version }}
  {{- end }}
  refreshAfter: {{ .refreshInterval }}
  destination:
    name: {{ .secretName }}
    create: true
{{- if .transformation }}
    transformation:
      templates:
        {{ .transformation.key }}:
          text: |
            {{ "{{-" }} printf "%s" ({{ .transformation.function }} (get .Secrets "{{ .transformation.key }}")) {{ "-}}" }}
{{- end }}
---
{{- end }}
{{- end }}

{{- if .Values.secrets.dynamicSecrets.enabled }}
{{- $dynamicSecretsEngineMountPath := .Values.secrets.dynamicSecrets.mountPath -}}
{{- range .Values.secrets.dynamicSecrets.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .name }}
  labels:
    simpletrip: {{ $serviceName }}
spec:
  namespace: {{ $namespace }}
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ $dynamicSecretsEngineMountPath }}
  path: {{ .permissionsRolePath }}
  renewalPercent: {{ .renewalPercent }}
  destination:
    name: {{ .name }}
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ $serviceName }}
{{- end }}
{{- end }}
