{{- if .Values.secrets.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    simpletrip: {{ include "common.name" . }}
    imageTag: {{ quote .Values.image.tag }}
spec:
  namespace: admin/yiluhub/
  # vaultAuthRef is the name of the Vault Auth resource deployed as part of the vault secrets operator. The value is namespace prefixed
  vaultAuthRef: vault-secrets-operator/default
  mount: aws/secret-engine
  path: {{ .Values.secrets.permissions }}
  destination:
    name: {{ .Values.secrets.name }}
    create: true
  rolloutRestartTargets:
    - deployment: {{ include "common.name" . }}

---
# The name of this service account must match that defined in the vault secrets operator namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-secrets-operator-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets-operator-sa-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: vault-secrets-operator-sa
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-secrets-operator-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
