{{- $serviceName := (include "common.name" .) -}}
{{- $namespace := .Values.secrets.vault.namespace -}}
{{- $vaultAuthRef := .Values.secrets.vault.authRef -}}
{{- $dynamicSecretsEngineMountPath := .Values.secrets.dynamicSecrets.mountPath -}}

---
{{- if .Values.secrets.staticSecrets.enabled }}
{{- range .Values.secrets.staticSecrets.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .secretName }}
  labels:
    simpletrip: {{ $serviceName }}
spec:
  namespace: {{ $namespace }}
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ .mountPath }}
  type: {{ .type }}
  path: {{  .secretPath }}
  version: {{  .version | default "1" }}
  refreshAfter: {{ .refreshInterval }}
  destination:
    name: {{ .secretName }}
    create: true
{{- end }}
{{- end }}
---
{{- if .Values.secrets.dynamicSecrets.enabled }}
{{- range .Values.secrets.dynamicSecrets.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .name }}
  labels:
    simpletrip: {{ $serviceName }}
spec:
  namespace: {{ $namespace }}
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ $dynamicSecretsEngineMountPath }}
  path: {{ .permissionsRolePath }}
  renewalPercent: {{ .renewalPercent }}
  destination:
    name: {{ .name }}
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ $serviceName }}
{{- end }}
{{- end }}
