{{- $serviceName := (include "common.name" .) -}}
{{- $namespace := .Values.secrets.vault.namespace -}}
{{- $vaultAuthRef := .Values.secrets.vault.authRef -}}
{{- $dynamicSecretsEngineMountPath := .Values.secrets.dynamicSecrets.mountPath -}}
{{- $staticSecretsEngineMountPath := .Values.secrets.staticSecrets.mountPath -}}
{{- $staticSecretsName := .Values.secrets.staticSecrets.secretName -}}

---
{{- if .Values.secrets.staticSecrets.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $staticSecretsName }}
  labels:
    simpletrip: {{ $serviceName }}
spec:
  namespace: {{ $namespace }}
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ $staticSecretsEngineMountPath }}
  type: kv-v2
  path: {{  .Values.secrets.staticSecrets.secretPath }}
  version: {{  .Values.secrets.staticSecrets.version | default "1" }}
  refreshAfter: {{ .Values.secrets.staticSecrets.refreshInterval }}
  destination:
    name: {{ $staticSecretsName }}
    create: true
{{- end }}

---
{{- if .Values.secrets.dynamicSecrets.enabled }}
{{- range .Values.secrets.dynamicSecrets.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .name }}
  labels:
    simpletrip: {{ $serviceName }}
spec:
  namespace: {{ $namespace }}
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ $dynamicSecretsEngineMountPath }}
  path: {{ .permissionsRolePath }}
  renewalPercent: {{ .renewalPercent }}
  destination:
    name: {{ .name }}
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ $serviceName }}
{{- end }}
{{- end }}
