{{- $serviceAccount := lookup "v1" "ServiceAccount" .Release.Namespace "vault-secrets-operator-sa" -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "vault-secrets-operator-sa-secret" -}}
{{- $clusterRoleBinding := lookup "rbac.authorization.k8s.io/v1" "ClusterRoleBinding" "" "{{ .Release.Name }}-role-tokenreview-binding" -}}
{{- $serviceName := (include "common.name" .) -}}
{{- $namespace := .Values.secrets.vault.namespace -}}
{{- $vaultAuthRef := .Values.secrets.vault.authRef -}}
{{- $dynamicSecretsEngineMountPath := .Values.secrets.dynamicSecrets.mountPath -}}
{{- $staticSecretsEngineMountPath := .Values.secrets.staticSecrets.mountPath -}}
{{- $staticSecretsName := .Values.secrets.staticSecrets.secretName -}}

---
{{- if .Values.secrets.staticSecrets.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $staticSecretsName }}
  labels:
    simpletrip: {{ $serviceName }}
spec:
  namespace: {{ $namespace }}
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ $staticSecretsEngineMountPath }}
  type: kv-v2
  path: {{  .Values.secrets.staticSecrets.secretPath }}
  version: {{  .Values.secrets.staticSecrets.version | default "1" }}
  refreshAfter: {{ .Values.secrets.staticSecrets.refreshInterval }}
  destination:
    name: {{ $staticSecretsName }}
    create: true
{{- end }}

---
{{- if .Values.secrets.dynamicSecrets.enabled }}
{{- range .Values.secrets.dynamicSecrets.secrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .name }}
  labels:
    simpletrip: {{ $serviceName }}
spec:
  namespace: {{ $namespace }}
  vaultAuthRef: {{ $vaultAuthRef }}
  mount: {{ $dynamicSecretsEngineMountPath }}
  path: {{ .permissionsRolePath }}
  destination:
    name: {{ .name }}
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ $serviceName }}
{{- end }}
{{- end }}

---
{{- if not $serviceAccount }}
# The name of this service account must match that defined in the vault secrets operator namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secrets.vault.vaultSecretsOperatorName }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}

---
{{- if not $secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.vault.vaultSecretsOperatorName }}-sa-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.secrets.vault.vaultSecretsOperatorName }}-sa
type: kubernetes.io/service-account-token
{{- end }}

---
{{- if not $clusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-role-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: {{ .Values.secrets.vault.vaultSecretsOperatorName }}-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
