# Inject secrets
secrets:
  dynamicSecrets:
    enabled: true
    mountPath: "aws/secret-engine"
    secrets:
      - name: "hede"
        type: aws
        permissionsRolePath: "" # example creds/service-read
        renewalPercent: 70 # Renew the secret when it's TTL reaches this value in % (percentage)
  staticSecrets:
    enabled: true
    secrets:
      - secretName: "booking-secrets" # example worldshop-secrets, this is the name of the secret created in k8s
        secretPath: "bookings" # example worldshop
        mountPath: "kv/services/secrets"
        refreshInterval: 1h
        version: ~ # set it to null to always return latest version
        type: kv-v2
        secretKeys:
          - AUTHORIZATION_TOKEN
          - WORLDSHOP_PRICING_API
      - secretName: "payment-secrets" # example worldshop-secrets, this is the name of the secret created in k8s
        secretPath: "payments" # example worldshop
        mountPath: "kv/services/secrets"
        refreshInterval: 1h
        version: ~ # set it to null to always return latest version
        type: kv-v2
        transformation:
          key: application.yaml
          function: b64dec


aws:
  enabled: false


environmentSecrets:
  - name: SONARQUBE_TOKEN
    secretKeyRef:
      name: sonarqube-secrets
      key: token
  - name: AWS_S3_BUCKET_ACCESS_KEY_ID
    secretKeyRef:
      name: bookings-s3-secrets
      key: access_key_id
  - name: AWS_S3_BUCKET_ACCESS_SECRET
    secretKeyRef:
      name: bookings-s3-secrets
      key: access_secret

extraVolumeMounts:
  - name: booking-secrets
    mountPath: /etc/secrets

extraVolumes:
  - name: booking-secrets
    secret:
      secretName: booking-secrets

extraEnv:
  - name: SPRING_CONFIG_ADDITIONAL-LOCATION
    value: file:/etc/secrets/
