name: Pull Request Workflow
run-name: ${{ github.actor }} has triggered a Pull Request Workflow! 🚀

on:
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-code-analysis:
    name: Linting
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run linter
        run: helm lint yilu-common --set image.tag="test" --set serviceName="ci-test"
